# 服务器配置
server:
  host: "127.0.0.1"
  port: 7768

# 数据库配置
database:
  host: "127.0.0.1"
  port: 3306
  user: "danmaku_user"
  password: "change_me_in_env" # 请修改为您的数据库密码, 建议通过环境变量覆盖
  name: "danmaku_db"

# JWT (JSON Web Token) 配置
jwt:
  secret_key: "change_me_please" # 请务必修改为一个复杂且唯一的密钥, 建议通过环境变量覆盖
  algorithm: "HS256"
  access_token_expire_minutes: 1440 # 令牌有效期（分钟），例如 1天
